neighborhood_shops_api/config/routes.rb
Rails.application.routes.draw do
  resources :shops

end

neighborhood_shops_api/app/models/shop.rb
class Shop < ActiveRecord::Base

  #添付ファイルアップロードに関する設定
  has_attached_file :image,
  :styles => {
    :small => "50x50#",
    :medium => "300x200#",
    :large => "640x640#"
  },
  :storage        => :s3,
  :s3_permissions => :private,
  :s3_credentials => "#{Rails.root}/config/s3.yml",
  :path           => ":class/:attachment/:id/:style.:extension"

  #データに関するバリデーション
  validates :title, presence: true
  validates :category, presence: true
  validates :catch, presence: true
  validates :detail, presence: true
  validates :image, presence: true

  #画像ファイルに関するバリデーション
  validates_attachment_content_type :image,
  :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  validates_attachment_size :image,
  :less_than => 2.megabytes

  #S3の画像ファイルURLを取得する（管理画面でのみの使用）
  def authenticated_image_url(style)
    image.s3_object(style).url_for(:read, :secure => true)
  end

end

neighborhood_shops_api/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  if Rails.env == "production"
    BASIC_AUTH_USER_NAME     = ENV['BASIC_AUTH_USER_NAME']
    BASIC_AUTH_USER_PASSWORD = ENV['BASIC_AUTH_USER_PASSWORD']
  elsif Rails.env == "development"
    BASIC_AUTH_USER_NAME     = 'user'
    BASIC_AUTH_USER_PASSWORD = 'password'
  end
end

neighborhood_shops_api/app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: BASIC_AUTH_USER_NAME, password: BASIC_AUTH_USER_PASSWORD, only: [:new, :show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:title, :category, :catch, :detail, :image)
    end
end

neighborhood_shops_api/app/helpers/application_helper.rb
module ApplicationHelper
end

neighborhood_shops_api/app/helpers/shops_helper.rb
module ShopsHelper
end

neighborhood_shops_api/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NeighborhoodShopsApi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

neighborhood_shops_api/app/views/shops/_form.html.erb
<%= form_for(@shop) do |f| %>
  <% if @shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% @shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :catch %><br>
    <%= f.text_field :catch %>
  </div>
  <div class="field">
    <%= f.label :detail %><br>
    <%= f.text_area :detail %>
  </div>
  <!-- 画像アップロード用のf.file_fieldを追記する -->
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

neighborhood_shops_api/app/views/shops/edit.html.erb
<h1>Editing shop</h1>

<%= render 'form' %>

<%= link_to 'Show', @shop %> |
<%= link_to 'Back', shops_path %>

neighborhood_shops_api/app/views/shops/index.html.erb
<h1>Listing shops</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Category</th>
      <th>Catch</th>
      <th>Detail</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= shop.title %></td>
        <td><%= shop.category %></td>
        <td><%= shop.catch %></td>
        <td><%= shop.detail %></td>
        <td><%= image_tag(shop.image(:small)) %></td>
        <td><%= link_to 'Show', shop %></td>
        <td><%= link_to 'Edit', edit_shop_path(shop) %></td>
        <td><%= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shop', new_shop_path %>

neighborhood_shops_api/app/views/shops/new.html.erb
<h1>New shop</h1>

<%= render 'form' %>

<%= link_to 'Back', shops_path %>

neighborhood_shops_api/app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @shop.title %>
</p>

<p>
  <strong>Category:</strong>
  <%= @shop.category %>
</p>

<p>
  <strong>Catch:</strong>
  <%= @shop.catch %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @shop.detail %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@shop.image(:medium)) %>
</p>

<%= link_to 'Edit', edit_shop_path(@shop) %> |
<%= link_to 'Back', shops_path %>